export const enum Errors {
  ERROR_INVALID_USER_DATA = "ERROR_INVALID_USER_DATA",
  ERROR_USERNAME_ALREADY_EXISTS = "ERROR_USERNAME_ALREADY_EXISTS",
  ERROR_EMAIL_ALREADY_EXISTS = "ERROR_EMAIL_ALREADY_EXISTS",
}
