export const enum Errors {
  ERROR_INTERNAL_SERVER_ERROR = "ERROR_INTERNAL_SERVER_ERROR",
  ERROR_INVALID_USER_DATA = "ERROR_INVALID_USER_DATA",
  ERROR_USERNAME_ALREADY_EXISTS = "ERROR_USERNAME_ALREADY_EXISTS",
  ERROR_EMAIL_ALREADY_EXISTS = "ERROR_EMAIL_ALREADY_EXISTS",
  ERROR_SERVER_NAME_ALREADY_EXISTS = "ERROR_SERVER_NAME_ALREADY_EXISTS",
  ERROR_SERVER_NOT_FOUND = "ERROR_SERVER_NOT_FOUND",
  ERROR_USER_NOT_FOUND = "ERROR_USER_NOT_FOUND",
  ERROR_USER_ALREADY_IN_SERVER = "ERROR_USER_ALREADY_IN_SERVER",
}
