version: "3"

services:
  service-gateway:
    extends:
      file: docker-compose.template.yml
      service: service-template
    ports:
      - ${GATEWAY_PORT:-3000}:3000
    command: npx nx serve service-gateway

  service-authentication:
    extends:
      file: docker-compose.template.yml
      service: service-template
    command: npx nx serve service-authentication

  service-authorization:
    extends:
      file: docker-compose.template.yml
      service: service-template
    command: npx nx serve service-authorization

  service-account:
    extends:
      file: docker-compose.template.yml
      service: service-template
    command: npx nx serve service-account

  service-server:
    extends:
      file: docker-compose.template.yml
      service: service-template
    command: npx nx serve service-server

  # service-message:
  #   extends:
  #     file: docker-compose.template.yml
  #     service: service-template
  #   command: npx nx serve service-message

  # service-search-message:
  #   extends:
  #     file: docker-compose.template.yml
  #     service: service-template
  #   command: npx nx serve service-search-message

  service-file:
    extends:
      file: docker-compose.template.yml
      service: service-template
    command: npx nx serve service-file

  service-role:
    extends:
      file: docker-compose.template.yml
      service: service-template
    command: npx nx serve service-role

volumes:
  mono-node-modules: null
