version: "3"

services:
  service-template:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DEV_PLATFORM=DOCKER
    volumes:
      - ./:/app
      #- mono-node-modules:/app/node_modules
