version: "3"

services:

  service-gateway:
    extends:
      file: docker-compose.template.yml
      service: service-template
    ports:
      - ${GATEWAY_PORT:-3000}:3000
    command: npx nx serve service-gateway

  service-authentication:
    extends:
      file: docker-compose.template.yml
      service: service-template
    command: npx nx serve service-authentication

volumes:
  mono-node-modules: null
