apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
  labels:
    app: client
spec:
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: client
          image: europe-west9-docker.pkg.dev/harmony-383520/harmony/harmony-client:stable
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 200m
              memory: 256Mi

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: client-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: client
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60

---
apiVersion: v1
kind: Service
metadata:
  name: client-svc
spec:
  type: NodePort
  selector:
    app: client
  ports:
    - protocol: TCP
      port: 60080
      targetPort: 80

---
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: client-cert
spec:
  domains:
    - harmony.vg

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: client-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: harmony-global-ip
    networking.gke.io/managed-certificates: "client-cert"
spec:
  rules:
  - host: harmony.vg
    http:
      paths:
      - pathType: ImplementationSpecific
        backend:
          service:
            name: client-svc
            port:
              number: 60080
