apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: service-notification-cert
spec:
  domains:
    - ws.harmony.vg

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: service-notification-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: harmony-notification-ip
    networking.gke.io/managed-certificates: service-notification-cert
    # nginx.ingress.kubernetes.io/proxy-connect-timeout: "3600s"
    # nginx.ingress.kubernetes.io/proxy-read-timeout: "200000"
    # nginx.ingress.kubernetes.io/proxy-send-timeout: "30000"
spec:
  rules:
    - host: ws.harmony.vg
      http:
        paths:
          - pathType: ImplementationSpecific
            backend:
              service:
                name: service-notification-svc
                port:
                  number: 60000
