apiVersion: v1
kind: Service
metadata:
  name: service-notification-svc
spec:
  type: NodePort
  selector:
    app: service-notification
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
