apiVersion: v1
kind: Service
metadata:
  name: service-notification
spec:
  type: NodePort
  selector:
    app: service-notification
  ports:
    - protocol: TCP
      port: 60000
      targetPort: 3001
