apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-notification
  labels:
    app: service-notification
spec:
  selector:
    matchLabels:
      app: service-notification
  template:
    metadata:
      labels:
        app: service-notification
    spec:
      containers:
        - name: service-notification
          image: europe-west9-docker.pkg.dev/harmony-383520/harmony/harmony-service-notification:stable
          imagePullPolicy: Always
          ports:
            - containerPort: 3001
          env:
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: api-config
                  key: NODE_ENV
            - name: PORT
              value: "3001"
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 200m
              memory: 256Mi

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: service-notification-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: service-notification
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
