name: Kubernetes Rolling Update

on:
  push:
  workflow_dispatch: {}
  workflow_run:
    workflows: ["Build and push Docker images"]
    branches: ["main"]
    types:
      - completed

env:
  GKE_CLUSTER: harmony-gke
  GKE_ZONE: europe-west9

jobs:
  generate-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.affected-services.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          cache: "npm"
          node-version-file: ".nvmrc"

      - name: "Install NX Dependencies"
        run: npm install nx

      - name: Determine affected application
        id: affected-services
        run: |
          output=$(npx nx print-affected --type=app --base=HEAD~1)
          services=$(echo "$output" | jq '.projects')
          echo "matrix=$(jq -r -c . <<< "$services")" >> $GITHUB_OUTPUT

      - name: Check matrix
        run: jq . <<< '${{ steps.affected-services.outputs.matrix }}'

  deploy:
    name: Redeploy service
    runs-on: ubuntu-latest
    permissions: write-all
    needs: generate-matrix
    strategy:
      matrix:
        service: ${{ fromJSON(needs.generate-matrix.outputs.matrix) }}
    steps:
      - id: "auth"
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Set up Kubernetes credentials
        uses: google-github-actions/get-gke-credentials@v1
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_ZONE }}

      - name: "Deploy to Kubernetes"
        run: |
          kubectl set image deployment/${{ matrix.service }} ${{ matrix.service }}=europe-west9-docker.pkg.dev/harmony-383520/harmony/harmony-${{ matrix.service }}:stable
          kubectl rollout status deployment/${{ matrix.service }}
