name: "Google cloud authentication"

on:
  workflow_call:
    inputs:
      workload_identity_provider:
        description: "The workload identity provider to use for authentication"
        required: true
        type: string
      service_account:
        description: "The service account key to use for authentication"
        required: true
        type: string


jobs:
  google-cloud-auth:
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest
    steps:
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: ${{ inputs.workload_identity_provider }}
          service_account: ${{ inputs.service_account }}
