name: Apply Kubernetes configuration

on:
  workflow_dispatch: {}
  push:
    branches:
      - main
    paths:
      - "kubernetes/**"

env:
  GKE_CLUSTER: harmony-gke
  GKE_ZONE: europe-west9

jobs:
  apply-kubernetes-configuration:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          cache: "npm"
          node-version-file: ".nvmrc"

      - id: "auth"
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Set up Kubernetes credentials
        uses: google-github-actions/get-gke-credentials@v1
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_ZONE }}

      - name: Apply Kubernetes configuration
        run: |
          kubectl apply -f kubernetes/

